### ISSUE TITLE
Enable Dependabot for Security & Dependency Management

### ISSUE THREAD

**Issue by DJBlackEagle** [DJBlackEagle/code-style#13]
### ⚠️ Is there an existing issue for this?

- [x] I have searched the existing issues

### ⚖️ Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/DJBlackEagle/code-style/blob/main/CODE_OF_CONDUCT.md)

### 🏷️ Severity Level

❕ Medium - Moderate improvement with noticeable benefits

### 🗃️ Category

GitHub Actions or Workflows

### 📝 Detailed Description

Dependabot should be enabled to automatically check for updates to dependencies within the repository. 
This ensures that all dependencies are kept up-to-date, reducing security risks and keeping the project in sync with the latest stable versions of libraries.

A `.github/dependabot.yml` configuration file should be created to define the update strategy for npm dependencies.

### ✅ Expected Outcome or Improvement

- Dependabot regularly checks for updates to npm dependencies.
- Automatic pull requests are created for dependency updates.
- A clear update schedule is defined (e.g., weekly updates).
- Security patches are applied promptly.
- The repository remains up-to-date with the latest library versions.

### ➕ Additional Context (Optional)

- Reference to GitHub's [Dependabot documentation](https://docs.github.com/en/code-security/dependabot).
- Example configuration file:

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "eslint"
        versions: ["<8.0.0"]
```

### 🌀 Other Details (Optional)

- Dependabot should be configured to ignore major version updates unless explicitly required.
- CI/CD workflows should be tested to ensure compatibility with updates.
- Auto-merging of minor updates can be enabled for smoother maintenance.
