### ISSUE TITLE
Set Up Pull Request Checks (Linting, Prettier)

### ISSUE THREAD

**Issue by DJBlackEagle** [DJBlackEagle/code-style#14]
### ⚠️ Is there an existing issue for this?

- [x] I have searched the existing issues

### ⚖️ Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/DJBlackEagle/code-style/blob/main/CODE_OF_CONDUCT.md)

### 🏷️ Severity Level

❕ Medium - Moderate improvement with noticeable benefits

### 🗃️ Category

GitHub Actions or Workflows

### 📝 Detailed Description

The repository currently does not enforce linting, formatting, and testing on pull requests. This means that code contributions might introduce inconsistencies in code style or failing tests.

Setting up a **GitHub Actions workflow** to run **ESLint and Prettier** on every pull request will ensure:
- Code is formatted correctly before merging.
- Linting errors are caught early.

### ✅ Expected Outcome or Improvement

- A GitHub Actions workflow is created to run **linting and Prettier checks** on all pull requests.
- Pull requests that fail these checks **cannot be merged** until the issues are fixed.
- Developers receive clear feedback on linting, formatting, or test failures in the pull request.
- The repository maintains a high standard of code quality.

### ➕ Additional Context (Optional)

1. **Create a GitHub Actions workflow file (`.github/workflows/pr-checks.yml`).**
2. **Add a step for ESLint to check linting issues:**
   ```yaml
   - name: Run ESLint
     run: npx eslint .
   ```
3. **Add a step for Prettier to check formatting:**
   ```yaml
   - name: Run Prettier
     run: npx prettier --check .
   ```
4. **Ensure that the workflow runs on every pull request (`on: pull_request`).**
5. **Test the setup to confirm that pull requests are blocked if checks fail.**
6. **Update documentation to inform contributors about the checks.**

### 🌀 Other Details (Optional)

- Reference: [GitHub Actions Documentation](https://docs.github.com/en/actions)
- Example of a working GitHub Actions configuration:
  ```yaml
  name: Pull Request Checks
  on: pull_request
  jobs:
    checks:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Run ESLint
          run: npx eslint .

        - name: Run Prettier
          run: npx prettier --check .
  ```
- Having **pre-commit hooks** with Husky and Lint-Staged is recommended for local enforcement before pushing changes.
